### ISSUE TITLE
Lastest template failed to run

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.templates#11]
I'm not sure perhaps I did something wrong but if I execute following commands:
dotnet new -i "cloudscribe.templates::*"
dotnet new cloudscribe -D NoDb -S a -L true
dotnet restore
 
then I got following errors:
`error NU1605: Detected package downgrade: Microsoft.EntityFrameworkCore.Tools from 2.1.1 to 2.1.0. Reference the package directly from the project to select a different version.`

`error NU1605:  Blog -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.EntityFrameworkCore.Tools (>= 2.1.1 && < 2.2.0)`

`error NU1605:  Blog -> Microsoft.EntityFrameworkCore.Tools (>= 2.1.0)`

**Comment by cheverdyukv** [comment]
If I put Version="2.1.0"  to 
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />
then it works

**Comment by joeaudette** [comment]
this should be fixed in version 1.0.41
https://www.nuget.org/packages/cloudscribe.templates/1.0.41

**Comment by cheverdyukv** [comment]
Fixed
