### ISSUE TITLE
Strange

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.templates#18]
I'm not sure if this is a problem but after executing following commands:
dotnet new -i "cloudscribe.templates::*"
dotnet new cloudscribe -D NoDb -S a -L true
 file launchSettings.json contains following:
    "**Bloglication1**": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }

in previous version it creates following in same place:
    "Blog": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:40258/"
    },
    "Blog Production": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      },
      "applicationUrl": "http://localhost:40258/"
    }

**Comment by joeaudette** [comment]
that is not related. If you make a new project with the standard Microsoft template it uses https by default so I made our template do the same.
and launchsetings is only used by VS not in production.

**Comment by cheverdyukv** [comment]
Sorry, my bad I wasn't clear. There are 2 issues:
1. There is no production section anymore.
2. It has strange name: Bloglication1

**Comment by joeaudette** [comment]
I guess I did remove that, but the standard project templates don't add that either. I will add it back next release of the template, but you can easily add it yourself

    "Bloglication1-production": {
    "commandName": "Project",
    "launchBrowser": true,
    "applicationUrl": "https://localhost:5001;http://localhost:5000",
    "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
        }
    }

**Comment by cheverdyukv** [comment]
It is not a problem for me, I just thought something bad happened to template and it is my I did report it. If this is not a problem I will close it

**Comment by joeaudette** [comment]
fyi, I went ahead and published the fix for this issue https://www.nuget.org/packages/cloudscribe.templates/1.0.52

**Comment by cheverdyukv** [comment]
It looks great!
