### ISSUE TITLE
navigation.xml stated that it is utf-16 but is it really utf-16?

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.templates#24]
I checked old version and it looks like utf-16 but new one looks like utf-8 to me. Not sure if this is important

**Comment by joeaudette** [comment]
I think I caused that, I updated the file itself to utf-8 but didn't realize there was a declaration in the file itself for utf-16.

The problem I was trying to solve at the time was that git/github was treating utf-16 xml file as binary and not showing diffs. 

So probably I will just change the declaration in the file to utf-8 so it matches the actual file format.

**Comment by joeaudette** [comment]
the file encoding and the declaration have been updated to utf-8
