### ISSUE TITLE
Broken font-awesome in 1.72

### ISSUE THREAD

**Issue by nirkbirk** [cloudscribe/cloudscribe.templates#42]
Hi Joe,

The commit to fix #39 has broken font-awesome in some of the themes of projects created from the template version 1.72.

It appears that the new fontawesome-all.css file does not change the font family for .fa, .far, and .fas css classes, so all of the characters show as empty boxes.

Steps to reproduce:

1. Create a new cloudscribe project using the template
2. Set the site theme to 'default' through the administration panel
3. Font-awesome icons across the site (including the admin menu icons) will appear as white boxes

Most of the shared themes contain a copy of the old fontawesome-all.css file and font files and are therefore unaffected by this bug. However, I believe they won't be affected by the fix from issue #39 either.

Thanks

**Comment by joeaudette** [comment]
Thanks for the bug report! When I updated the fontawesome-all.css I assumed that file from their download had everything but it was missing the @font-face urls at the bottom which I found were in the all,css in their download.

I've updated it and published v 1.73.

I'm not really trying to keep the bootswatch themes updated to new versions of fontawesome, I leave that to those who choose to use those themes. Mainly the custom1 theme is the one I use in my projects as it is setup to use sass in the app-scss folder with a gulp file to process it into css. Custom1 and default both use the same wwwroot/webfonts but custom1 doesn't use the fontawesome-all.css, it has the fontawesome in its own sass setup to bundle it in the same css file with the idea being that you can edit the _icons.scss file and comment out the ones you aren't using to reduce the css bloat. "default" isn't really a theme per se, it just uses the default _Layout.cshtml file from the main Views/Shared folder whereas real themes have their own _Layout in the theme/Shared folder. So I think default is the only one affected and really I wouldn't expect people to use that, but nevertheless good to fix that. I've configured it to make the custom1 the theme set on new sites when they are created so in a sense it is the default theme.

Thanks again!

**Comment by nirkbirk** [comment]
Thanks for your superb work and quick response. I only noticed the issue when I was creating a multi-tenant site earlier today. When you create a second site, it uses the default 'theme', so when all the fa icons disappeared on the new site I was a little confused!

Thanks for taking the time to write an explanation too.

Cheers,
Nick

**Comment by joeaudette** [comment]
Ah, that makes sense. The initial site uses custom1 but I can't make custom1 the default for additional sites since it is a private theme. I should probably tidy up the default one a little for that reason, will try to get to it soon. I noticed the site title link isn't pretty in the default theme.
Thanks!
