### ISSUE TITLE
SimpleContent requires sitefiles folder even when UseSharedThemes = true

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.templates#49]
In my application all my tenants using the same theme. I put this in `appsettings.json`:
`    "UserPerSiteThemes": "false",
    "UseSharedThemes": "true"`
and I decided to delete `sitefiles ` directory. Main reason to delete that I will not use it and I have to ignore it every time during synchronization etc.

But in this case site fails with `System.IO.DirectoryNotFoundException: 'C:\Projects\Blog\New\Blog\sitefiles\s1\themes\custom1\wwwroot\'` and not rendering at all.

Steps to reproduce. Create new site using this:
`dotnet new cloudscribe -D NoDb -S a -L true`

move custom1 theme from `sitefiles\s1\themes` to `SharedThemes`, delete/rename `sitefiles` directory and apply changes to `appsettings.json`:
`    "UserPerSiteThemes": "false",
    "UseSharedThemes": "true"`
and run app. You will see .Net Core screen of death. 

I understand that this is low priority but I spent few hours trying to understand why it doesn't work because I knew that  `sitefiles` directory not suppose to be used all.

**Comment by joeaudette** [comment]
Themes are self contained things, what file names they use for css is not important that they match other themes. You can name files whatever you like in custom themes, the documentation is correctly indicating the important differences. The shared themes are all bootswatch themes so they are all very similar to each other. The custom1 theme that is private is different, it is designed to less  you use bootstrap sass variables and uses a gulp file to produce the output css file. There is no reason it needs to use the same file names as the bootswatch themes, but the fact it uses different file names is also not important, it could have used the same names but it was not based on the bootswatch themes,

The bootswatch themes use a site.css file to oveeride some bootstrap things, whereas custom1 becuase it uses sass and combines multiple files into one, only has style.css as its output and that contains bootstrap plus site specific css all in one.

**Comment by joeaudette** [comment]
There were actually some outdated things in the documentation, it was written back during the time of boostrap3 and when the views in nugets were embedded resources. Nowadays views in nugets are pre-compiled rather than served as embedded resource files.

I've also added detailed information about the custom1 theme and how to use and customize it.
https://www.cloudscribe.com/themes-and-web-design

**Comment by cheverdyukv** [comment]
I was trying to say that custom1 theme has mention of IE11 and even including .css file for it. Also custom1 theme including only one .css file but Shared theme includes 3 .css file. But documentation for section "Differences Between Private Themes and Shared Themes" states that both themes include 2 .css file.

Perhaps I got it wrong but after reading I would assume that in general these themes should be almost identical.

**Comment by joeaudette** [comment]
The documentation is about difference when making a theme what you need to know to make a shared vs private theme. It is not about describing all differences of included themes. For individual themes there are no rules about file names or how many files or what other things it may be trying to accomplish.

The bootswatch themes are provided as examples of ready made themes, they were designed by [bootswatch team](https://bootswatch.com/) and adapted for cloudscribe by adding a _Layout.cshtml file and one extra sites.css to adapt the bootswatch as needed. If you want to customize those you are able to but I don't normally start new site designs using any of those.

The custom1 theme is the only theme I really tried to show possibilities to customize. It is the only theme I ever use to start a new custom theme. If I add features to custom1 it doesn't mean I need to add them to the bootswatch themes.

The bootswatch themes also include .scss files so if I were to make a custom theme based on that I would just copy the .scss files into custom1 and remove or replace or augment the standard bootstrap .scss files. But normally I just use custom1 and modify _variables.scss and other files as needed to make a new custom theme.

In a client project we had to support IE11 so I came up with a way to add a class to the body element for IE11 and include an extra file that made it easy for me to override styles for IE11 in that project. So I rolled it back into custom1 in case it useful in other projects. It is not an important feature and I don't feel any need to add it to every theme. Most projects I don't worry about IE11 and I don't care about the bootswatch themes in IE11. 
The only platform where IE11 is a concern is Windows 7 and soon Microsoft will release their new version of Edge based on Chromium and they will make that available for Windows 7 and they are already telling people [stop using IE11](https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732)

You are examining all differences between the themes and thinking they are important, they are not, the only important  thing about shared vs private themes is the extra taghelper param needed to resolve the resources from the shared theme wwwroot folder. All other differences are arbitrary and not relevant to private vs shared themes.

**Comment by cheverdyukv** [comment]
Thank you for this extensive explanation. Now it is much more clear what's going on there.
