### ISSUE TITLE
Should update template to use .net core 3.1 since 3.0 is EOL

### ISSUE THREAD

**Issue by joeaudette** [cloudscribe/cloudscribe.templates#60]
As in the title 3.1 is the long term support release and 3.0 is at the end of its support life. We should update the template to create apps that use 3.1.

**Comment by CrispinF** [comment]
@JimKerslake let's do this.

**Comment by zsubzwary** [comment]
@JimKerslake @joeaudette Has it been upgraded to **.Net Core 3.1**???

**Comment by JimKerslake** [comment]
@CrispinF  I think we still need to complete formal testing of the VSIX template (which is at Core 3.1) and get it uploaded to marketplace... it has existed for a while, but that final step needs doing.

**Comment by CrispinF** [comment]
Completed and published.
