### ISSUE TITLE
With folder multi-tenancy and "Pages and Blog with Home Controller as default route" the Pages don't work in child sites

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.templates#66]
The navigation.xml shipped with these choices includes this for the SimpleContent Pages:
```xml
       <NavNode key="Pages"
            url="/p"
            text="Articles"
            componentVisibility=""
            treeBuilderName="cloudscribe.SimpleContent.Services.PagesNavigationTreeBuilder"
            treeBuilderAppendToBuilderNode="true">
        <Children />
        </NavNode>
```
So if we create a second site, the Articles menu item navigates to the page in the first tenant.
One way to resolve this is to create a navigation.{guid}.xml for the second site (as per https://www.cloudscribe.com/different-menu-items-per-tenant ) and alter the url attribute to this:
url="/t1/p"
where t1 is the foldername I gave the tenant.
But this feels hard going for someone using cloudscribe for the first time, and they will probably think it's broken.
Can we do better? Maybe instead of the url attribute can we name a controller?

**Comment by JimKerslake** [comment]
Yes that works - I'll modify navigation.xml and include that in template source code - won't get deployed till we release a 5.0.1 at a future point.

**Comment by JimKerslake** [comment]
Tested this works in folder-name multi-tenancy
