### ISSUE TITLE
Testing issues for upgrade to Bootstrap5

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe.templates#75]

**Comment by CrispinF** [comment]
Something missing from this banner, when publish a Simple Content page:
![image](https://user-images.githubusercontent.com/10574730/152152899-022244a0-eaf6-4d51-9fdd-4b81602c87f4.png)


Page action buttons should be (were previously) on one row at desktop width:
![image](https://user-images.githubusercontent.com/10574730/152152987-5ff0aa1b-423f-4714-a003-851c4ff17e05.png)

**Comment by CrispinF** [comment]
Select an image in File Manager: a bit of a car crash layout:
![image](https://user-images.githubusercontent.com/10574730/152154334-28867cbe-244d-465b-bdb7-7b0fd0b50242.png)

Is Rename file supposed to be on the same row as the text control?

**Comment by CrispinF** [comment]
File Namager > Image select > Crop, needs a little layout work:
![image](https://user-images.githubusercontent.com/10574730/152155241-5dc7d5b8-6d05-4dbf-b9eb-e2e69aa718a3.png)


To align top of upper row of buttons, and add some vertical space between width and height controls.

**Comment by CrispinF** [comment]
- [ ] System Log: the error level buttons are now all stacked.

**Comment by CrispinF** [comment]
On the test site, Date of Birth is mandatory when creating new user. I don't think it was before??

**Comment by JimKerslake** [comment]
> On the test site, Date of Birth is mandatory when creating new user. I don't think it was before??

Quite a complex one here...

In the old version of the template, if you selected to install the user KVP, then a json file containing definitions of some extra KVP fields would be delivered, but (frustratingly) not wired up - so you needed to delve back into the docs to figure out how to wire them up.

In the current template now, that KVP config gets installed as a part of the appsettings.json (a long while ago we agreed this was the better location) - so they are properly wired up - so they actually take effect.

I'm not sure I ever really understood why - but that default set of new KVP properties has always been three fields that already exist in the Users table (firstname, lastname and DoB) so the effect of wiring them up is solely that the DoB field gets added (as 'required') to the New User registration screen (which lacks that field by default).  Presumably forename and surname do not get added, since they are already there.

DoB then also gets rendered a second time on the Edit User screen (which presumably already includes that field, even if KVP not installed)... though I've no idea why firstname and lastname are not similarly duplicated. 

I'd suggest it's probably less confusing to wire-up KVP with just one custom field that is clearly a custom field, not duplicates of pre-existing ones. I'm not actually sure why you would ever want to duplicate pre-existing user fields in Kvp...?

**Comment by CrispinF** [comment]
As discussed, let's not ship any activated KVP properties, but supply an example commented out, & ensure the wiring is there for it to work.

**Comment by CrispinF** [comment]
The Contact Form "Submit" button has incorrect markup (again!? -  this was bad after BS3 to 4). In fact I'm wondering whether this isn't the same issue (it is class "btn-default"), and I'm 99% sure we fixed that ages ago?

**Comment by CrispinF** [comment]
Content history controls have also gone full-screen and wrapped onto multiple lines, similar to other sets:
![image](https://user-images.githubusercontent.com/10574730/152701104-cb3eaee0-ca25-485c-8bfd-972accc95fa9.png)

**Comment by JimKerslake** [comment]
Contact form:  
looks like btn-default died along with Bootstrap3.
Guess we just want btn-primary here.

The template actually delivers an override for this view, so I'll fix that in both that override and the underlying Nuget equivalent.
Will have a scan about for any other stray uses of that class.

**Comment by JimKerslake** [comment]
New build just deployed, should address all above
