### ISSUE TITLE
Remove node-sass and fix Bootstrap 5 minor version in template 

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe.templates#80]
We're getting UI breakage if we allow the carat-ed version of Bootstrap stated in the package,json to auto-update to 5.2.x
So fix it back to 5.1.x for now, since the UI is fully tested at that.  Remove carat.

Also remove the gulp build dependency on deprecated node-sass and replace this with a reference to dart sass.

**Comment by StewartBellamy** [comment]
@JimKerslake - If using 5.1.x we'll need to get rid of the add user to role confirmation dialog.  https://github.com/cloudscribe/cloudscribe/issues/806
